version: "3.7"

services:
  pironman5:
    image: sunfounder/pironman5:${VARIANT:-base}
    container_name: pironman5
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      CONFIG_PATH: /data/config.json
    volumes:
      - ${APP_DATA_DIR:-./data}:/data
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
    labels:
      com.umbrel.app.name: "Pironman 5"
      com.umbrel.app.version: "1.3.0"
      com.umbrel.app.description: "Hardware monitoring & control for Pironman 5 HAT"
      com.umbrel.app.developer: "SunFounder"
      com.umbrel.app.website: "https://github.com/sunfounder/pironman5"
      com.umbrel.app.dependencies: ""
      com.umbrel.app.permissions: |
        - privileged
        - devices
        - host-network
